### ISSUE TITLE
Decide if we should have a compact set or not

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#1041]
Møte 2.nov 2023
Deltakere: @mimarz @Febakke @Thuneer @mrosvik @Barsnes 

For å unngå unødvendig kompleksitet går vi bort fra `compact`-setet og skriver heller en anbefaling på [Storefronten](https://www.designsystemet.no/grunnleggende/designelementer/sizing) om at du kan bruke Small-komponenter i kompakte grensesnitt. 

For overskriftsnivåer kan vi anbefale å bruke de minste headingene. I admingrensesnitt/verktøy ser vi at det uansett ikke benyttes så mange overskriftsnivåer.

Alle komponenter som kommer i ulike størrelser skal komme i 
- small
- medium (default)
- large

En medium komponent skal i utgangspunktet bruke medium `paragraph`, med unntak av de komponentene som skal oppleves mindre i forhold til de andre, eks: `tag`, `chip`, - der vil en medium `tag` bruke small `paragraph`, og en small `tag` bruke xsmall `paragraph`

```[tasklist]
### Tasks
- [x] Remove compact set from tokens
- [x] Add `small`, `medium`, `large` to all relevant components in figma
- [ ] https://github.com/digdir/designsystem/issues/1075
- [ ] https://github.com/digdir/designsystem/issues/1003
```
