### ISSUE TITLE
Skeleton: Develop React component

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#1101]
We should be able to use pass the `Skeleton` to a component using the `as` prop to fill that components size with skeleton loading animation.

## Tasks

- [x] The Skeleton Component should include a subtle animation to indicate activity.
  - [x] Opacity animation, with fading in and out
  - [x] The animation should be synchronized between component instances
  - [x] The component should support reduced motion which turns off the animation
- [x] The implementation is to be a compound component with 3 "variants":
  - [x] Skeleton.Circle
  - [x] Skeleton.Rectangle
  - [x] Skeleton.Text
- [x] The component should support sizing based on 4 cases:
  - [x] Height and width props should be optional, but override all other sizing if set
  - [x] The height should be inherited from a parent components fontsize
  - [x] The height and width should encompass any possible children
  - [x] Skeleton can be used in the "as" prop of other components (ex: Header as='Skeleton')
- [x] Rectangles should have rounded corners, text should have rounded side edges
- [x] Write tests
- [x] Write examples on the storybook page
