### ISSUE TITLE
Minor InputWrapper issues

### ISSUE THREAD

**Issue by TomasEng** [digdir/designsystem#129]
There are some issues with the internal `InputWrapper` component:

```[tasklist]
### Tasks
- [x] It is built on `div` components. Input components are normally inline, so this component should rather be built on `span`s.
- [x] Most of the styling on the wrapper should rather be applied to the wrapped object (using the `inputRenderer`'s `className` parameter). This will make the border clickable, like in a normal input, and height and outline properties will be easier to configure. We must find another solution for placing an icon beside it though (`:before`?).
- [ ] Outline should only be visible when using keyboard navigation.
```

**Comment by TomasEng** [comment]
> Is this being worked on? @TomasEng

Yes, @mimarz, I have started to look into it.

**Comment by mimarz** [comment]
I worked on solving this last fall in my previous project, so if you need anyone to spar with I am happy to help :) 

I ended up having a simple div around the `input`, relying on `focus-within` and absolute positioning containers for adornments/prefix/suffix. This worked best in terms of interaction, supporting all different variants of inputs ( custom and native, `<input readonly />` state was the most tricky)

**Comment by TomasEng** [comment]
Thanks for the tips, @mimarz! I will probably not have time to work further on this until tomorrow at earliest, so I'm not going to stop you if you want to do this yourself 😄(All I have done on this so far is just experimenting.) Otherwise I'll reach out when I continue.

**Comment by mimarz** [comment]
No worries! I have to much other stuff that needs to get done aswell. Trying to get the first draft of the new tokens, npm package and usage done & tested.

**Comment by mrosvik** [comment]
There should not be a tab-focus that is visible only for keyboard navigation.
