### ISSUE TITLE
Move search field component from Altinn's design system

### ISSUE THREAD

**Issue by TomasEng** [digdir/designsystem#198]
# Considerations
- Altinn/altinn-design-system/issues/255

# Tasks
```[tasklist]
- [ ] Move component code and unit tests
- [ ] Refactor CSS classes (we are not using the BEM convention)
- [ ] Create Storybook MDX file
```

**Comment by mimarz** [comment]
We have a new `Search` component in the works #88
