### ISSUE TITLE
Overview of products

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#2046]
**Produkter i Designsystemet:** 
- React-bibliotekt (RC1)
- Figma-biblioteket (RC1)
- CLI (kommandoverktøy) (RC1)
- Theme-pakke (Tokens som CSS-variabler)  (RC1)
- Github Template (RC1)
- CSS bibliotek (Beta)
- Temavelger (Beta)
- CDN (på sikt)
- Web components (på sikt)

```[tasklist]
### Tasks
- [ ] Oversikt (tabell) som viser alle produktene og status/versjon. Eller en artikkel med info om alle produktene og en tag bak hedingen som viser status.
- [ ] Legg lenke til temavelgeren fra forsiden (bolken om tema)
- [ ] Legg til lenke til Figma og React komponenter fra forsiden (bolken om komponenter)
- [ ] Legg til en ekstra bolk på forsiden med ekstra produkter som CLI++
```

**Comment by mrosvik** [comment]
Overview is here: https://www.designsystemet.no/no/fundamentals/introduction/about-the-design-system#hva-best%C3%A5r-designsystemet-av
