### ISSUE TITLE
Specification for: Navigation List

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#220]
### Related issues or relevant information?

![image](https://user-images.githubusercontent.com/1464915/223987741-6a33fe82-c291-465e-91d0-824c4268960a.png)

Related components: 
- [Header](https://github.com/digdir/designsystem/issues/216)

### Design tasks

- [ ] Design is fully specified in Figma
  - [ ] Design component with all relevant states
  - [ ] Do a accessibility test of the sketches
  - [ ] Functionality/animation is described and prototyped if relevant    
  - [ ] If there are used any svgs in this component is it available for the developer? [Link]
  - [ ] Link to Figma design: [Link]
  - [ ] Pasted screenshot from Figma below :point_down::skin-tone-2:  

### Development Tasks

- [ ] Implement in Storybook
- [ ] Make sure all variants/properties is possible to turn on/off
- [ ] Make sure the component is usable across different breakpoints/screen sizes

### Accessibility tasks

- [ ] WCAG-review

**Comment by mrosvik** [comment]
Not a part of planned components https://digdir.github.io/designsystem/?path=/docs/komponentoversikt--docs
