### ISSUE TITLE
Storefront beta

### ISSUE THREAD

**Issue by Thuneer** [digdir/designsystem#235]
List of tasks that are required for the first version of designsystemet.no

```[tasklist]
### Tasks
- [x] #225
- [x] #236
- [x] #237
- [ ] https://github.com/digdir/designsystem/issues/417
- [ ] #251
- [ ] https://github.com/digdir/designsystem/issues/419
- [ ] https://github.com/digdir/designsystem/issues/420
- [ ] https://github.com/digdir/designsystem/issues/457
- [ ] #239
- [ ] https://github.com/digdir/designsystem/issues/445
```

**Comment by mrosvik** [comment]
All tasks are done, the storefront is published on designsystemet.no
