### ISSUE TITLE
Add stylelint

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystem#244]
We want to add Stylelint for linting our css and keep clean code.

```[tasklist]
### Tasks
- [x] Add Stylelint with recommended configs (use .stylelintrc.js file ext for config)
- [x] Make sure to install the [Stylelint plugin for prettier](https://www.npmjs.com/package/prettier-stylelint)
- [x] Update vscode extension recommendation
- [x] Add styelint script in package.json
- [x] Update gh actions Check to include css linting
- [x] Run a first time "lint all with fix"
```
