### ISSUE TITLE
Select improvements

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystem#255]
List of identified improvements for our `Select` component.

```[tasklist]
### Tasks
- [ ] Decide on Select component features and behaviour with design
- [ ] Support Mac Voiceover for screenreader
- [ ] Support for deleting selected options on `Backspace` in Select
- [ ] Support for floating dropdown on Select
```

Notes
- #246

**Comment by bjosttveit** [comment]
When using single select, it will not show the label in the input field when the value is set from outside. Meaning that it cannot show a default value even though it is actually set. In app-frontend this means that when the page loads the currently selected language does not show up.

![image](https://user-images.githubusercontent.com/47412359/227926850-29206dca-ce57-4c12-9979-245ba0b82798.png)

**Comment by TomasEng** [comment]
The state handling in the component starts to become quite complex. I think we should try to move all this logic into a reducer with `useReducer`.

**Comment by mrosvik** [comment]
Duplicate of https://github.com/digdir/designsystem/issues/320

(Comment from @bjosttveit is moved to a single issue https://github.com/digdir/designsystem/issues/607 )
