### ISSUE TITLE
New component: Helptext

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystem#29]
### What component is it that needs specification?

Helptext
<img width="982" alt="Skjermbilde 2023-01-13 kl  09 09 24" src="https://user-images.githubusercontent.com/33222679/212270195-7d796f26-687a-4325-aa6c-7f13ab6b02a3.png">

### Tasks

[Link to correct placement in our Figma component library](https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/DDS---Core-Components?node-id=10351%3A59231&t=y8l6qKehH7jVgJXJ-1)
- [ ] Design is fully specified in Figma
  - [x] Design component with all relevant states
  - [x] Do a accessibility test of the sketches
  - [ ] Functionality/animation is described and prototyped if relevant 
  - [ ] Keyboard navigation specified   

### SVG
- [x] If there are used any svgs in this component is it available for the developer? 
  - The outlined and filled questionmark icon is a part of core icons

**Comment by Febakke** [comment]
@mrosvik @Thuneer 
Hei! gjort et forsøk på skyggen nå.
[Forslag på nye skyggestyles her](https://www.figma.com/file/eeznFkuH7UletQmhN174VR/DDS---Design-Tokens?node-id=777%3A4199&t=a80JeiHGDoiNMvkp-1)

<img width="796" alt="Skjermbilde 2023-01-13 kl  09 17 45" src="https://user-images.githubusercontent.com/33222679/212271639-96fab1c6-22ac-4d6c-aac8-dcc75de7ea07.png">
[Helptext komponenten](https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/DDS---Core-Components?node-id=10351%3A59231&t=y8l6qKehH7jVgJXJ-1)

**Comment by mrosvik** [comment]
Lurer på om vi skal ha den bittelitt sterkere? 20% ? 
:) 

![Image](https://user-images.githubusercontent.com/1464915/212654129-2d4c50ab-a188-4969-aab7-1628fbf4a588.png)

**Comment by Thuneer** [comment]
Enig, litt sterkere

**Comment by Febakke** [comment]
Hvor mange skygge styles tror dere vi trenger? Jeg har laget tre nå fordi det var tre fra før. Men jeg er litt usikker på når de forskjellige skal brukes. 

Endret lg til 20% nå. En del sterkere enn sm og md. [Figma](https://www.figma.com/file/eeznFkuH7UletQmhN174VR/DDS---Design-Tokens?node-id=777%3A4199&t=VmzoFVBOA9NYbtwq-1)

**Comment by mimarz** [comment]
We had a small discussion and feedback regarding allowed content inside the `HelperText` in PR #181 which might be relevant. We need to update guidelines accordingly.

**Comment by Camulos** [comment]
When I see this component, it registers for me as it supposed to ba an tooltip, with the functionality that is expected for tooltip (activates on mouse-over or (delayed) keyboard-focus). 

Some studies have shown that tooltip and helptexts that needs to be activated by the user, will for the most part be ignored. Depending on what the content is for helptext, it might be better to put it as part of the description for the component that uses the helptext component. If it were up to me, this component should be just removed from the design system or hidden as a "only if you really have to use it"-type of component.

We could perhaps add some of the tips/guidelines from here: https://www.nngroup.com/articles/tooltip-guidelines/ to try to reduce risk of important information in various services being hidden.

**Comment by Febakke** [comment]
In my mind I have always separated helptext and Tooltip. **Helptext** in the form of a "?" icon button the user can click on to get extra information, or a definition of a word for example is a common pattern in forms. A **tooltip** is activated on hover and are mainly used to explain icon buttons. For example in this texteditor on Github I can see what the different icons on top mean by hovering over them.
<img width="280" alt="Skjermbilde 2023-07-27 kl  10 51 10" src="https://github.com/digdir/designsystem/assets/33222679/d31ca409-4e1d-4c71-bbd4-e5f2af4ef858">

But! I agree with you that **the helptext component** as a concept is flawed.
* If you need to explain the meaning of a word. Maybe that is a sign that you need to find another word or way to explain yourself to the user.
* If you need to have a lot of text connected to a question, use a description that is visible for everyone always.
* They are often weird on smaller screens, and can in cases with a lot of content take up the whole screen. 
* I often find it hard to place them in the tab order in a form context when they connected to a field or a radio button. 

The problem is that we cant just remove it, since it is a expected component for many form developers and already in use on a lot of services. We need to work on how we present this component. As you said, we could start hiding it, at least we should give some warnings on the challenges with it and give them better alternatives trough guidelines.

On the other side, I am pro tooltip in complex UIs where you do not have the space to have text labels on all buttons. Tooltips can be very useful when used right.

**Comment by olemartinorg** [comment]
Linking in this thread regarding large amounts of text in the existing `HelpText` component:
- https://altinn.slack.com/archives/C02EVE4RU82/p1695893564632689

**Comment by mimarz** [comment]
Meeting 31.10.23

Helptext is ready and done in designsystemet.
