### ISSUE TITLE
Specification for: Fieldset

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#318]
### Design tasks

- [x] Design is fully specified in Figma
  - [x] Design component with all relevant states
  - [x] Do a accessibility test of the sketches
  - [x] Functionality/animation is described and prototyped if relevant    
  - [x] If there are used any svgs in this component is it available for the developer? [Link]
  - [x] Link to Figma design: [Link](https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/Felles-komponenter?node-id=8942%3A48179&t=7Q2N4sUdQGhFZrPh-1)
  - [x] Pasted screenshot from Figma below :point_down::
![image](https://user-images.githubusercontent.com/1464915/234204880-4331fca7-5e37-40ee-b4ad-71cecaab2085.png)

### Development Tasks

- [x] Implement in Storybook
- [x] Make sure all variants/properties is possible to turn on/off
- [x] Make sure the component is usable across different breakpoints/screen sizes

### Accessibility tasks

- [x] WCAG-review

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystem/issues/519
```
