### ISSUE TITLE
Improvements: TextArea

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#323]
```[tasklist]
### Tasks
- [x] Use the new tokens
- [x] Make sure style and states are updated according to new design in Figma
- [ ] https://github.com/digdir/designsystem/issues/678
- [ ] https://github.com/digdir/designsystem/issues/850
```

**Comment by mimarz** [comment]
Finished!
