### ISSUE TITLE
Specification for: Typography

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#324]
### Design tasks

- [Design is fully specified in Figma](https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/Felles-komponenter?node-id=9219%3A49405&t=7Q2N4sUdQGhFZrPh-1)
- Sizes is defined:

#### Heading

|                        | Font-size | Line-height | Weight |
| ---------------------- | --------- | ----------- | ------ |
| Heading - xlarge (h1)  | f5        | 1.3         | Medium |
| Heading - large (h2)   | f4        | 1.3         | Medium |
| Heading - medium (h3)  | f3        | 1.3         | Medium |
| Heading - small (h4)   | f2        | 1.3         | Medium |
| Heading - xsmall (h5)  | f1        | 1.3         | Medium |
| Heading - xxsmall (h6) | f0        | 1.3         | Medium |

#### Ingress

|                  | Font-size | Line-height | Weight  |
| ---------------- | --------- | ----------- | ------- |
| Ingress - medium | f1        | 1.6         | Regular |

#### Paragraph

|                    | Font-size | Line-height | Weight  |
| ------------------ | --------- | ----------- | ------- |
| Paragraph - large  | f1        | 1.5         | Regular |
| Paragraph - medium | f0        | 1.5         | Regular |
| Paragraph - small  | f-1       | 1.5         | Regular |
| Paragraph - xsmall | f-2       | 1.5         | Regular |

#### Label

|                | Font-size | Line-height | Weight |
| -------------- | --------- | ----------- | ------ |
| Label - large  | f1        | 1.3         | Medium |
| Label - medium | f0        | 1.3         | Medium |
| Label - small  | f-1       | 1.3         | Medium |
| Label - xsmall | f-2       | 1.3         | Medium |

#### Error message

|                        | Font-size | Line-height | Weight |
| ---------------------- | --------- | ----------- | ------ |
| Error message - medium | f0        | 1.3         | Medium |
| Error message - small  | f-1       | 1.3         | Medium |

### Development Tasks

```[tasklist]
### Related tasks
- [ ] https://github.com/digdir/designsystem/issues/364
- [x] Make sure all variants/properties is possible to turn on/off
- [x] Make sure the component is usable across different breakpoints/screen sizes
- [ ] https://github.com/digdir/designsystem/issues/498
- [ ] https://github.com/digdir/designsystem/issues/472
```

**Comment by mrosvik** [comment]
I guess `Typography` is done then 🎉 

Thanks for adding the correct spacings @framitdavid 🙌
