### ISSUE TITLE
Migrate Storybook component stories to new format

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystem#366]
Use this script to auto-migrate the story, this helps you with the basis: https://storybook.js.org/docs/react/migration-guide#storiesmdx-to-mdxcsf.

You will still need to edit and adjust the files thereafter to get our desired result. Look at the stories of `Accordion` and `Typography` for inspiration.

Make a new issue + PR for each component when starting this cleanup

Checklist for new docs:
- Make sure "show code" show correct code.
- Make sure props table is interactive and works. 
  - Have a look at Typography story for interactive props table on sub-components
- Do adjustments to types if needed
- Remove usages of `TokenTable`
- Add jsdocs to proptypes

 

```[tasklist]
### Tasks
- [ ] Migrate Textfield stories to new format
- [ ] https://github.com/digdir/designsystem/issues/369
- [ ] https://github.com/digdir/designsystem/issues/514
- [ ] https://github.com/digdir/designsystem/issues/581
- [ ] https://github.com/digdir/designsystem/issues/583
```

**Comment by mimarz** [comment]
Closing this as it will be solved as part of developing new updated version of the components for "felles designsystem".
