### ISSUE TITLE
Specification for: Native select

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#482]
### Design tasks

- [x] Design is fully specified in Figma:
https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/Felles-komponenter?type=design&node-id=7538%3A45657&t=S3Bcdw3x5cP6D0Kl-1

### Development Tasks

- [x] Develop React Component(s)
  - [x] Write stores and examples of use
  - [x] Write tests where applicable
  - [x] Make sure all variants/properties is possible to turn on/off
  - [x] Make sure the component is usable across different breakpoints/screen sizes

### Accessibility tasks

- [ ] WCAG-review
