### ISSUE TITLE
New component: Chip

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#49]
### Related information and research findings:
- [Chip in Entur design system](https://design.entur.no/komponenter/skjemaelementer/chips)
- [Chip in Aksel design system](https://aksel.nav.no/komponenter/core/chips)

### Chip specification

 - Should come in three variants: 
    - Chip 
       - Should support polymorphism (chip can be used as navigation links or buttons)
       - By default a button. Should always be an interactive element. For static elements use the [`Tag`](https://github.com/digdir/designsystem/issues/322) component instead. 
    - Chip removable
    - Chip toggle 
       - Single (radio)
       - Multi (checkbox)
 - Should come in two sizes in first version: xsmall, small. 
 - Should not support different colors
 - There should be a Chip.group component for grouping chips

```[tasklist]
### Tasks
- [x] Chip: Design Chip component in Figma
- [ ] https://github.com/digdir/designsystem/issues/360
- [ ] https://github.com/digdir/designsystem/issues/51
- [ ] https://github.com/digdir/designsystem/issues/367
- [ ] Chip: Multiselect already has a chip, make sure the same chip as developed here is used in multiselect.
```

## Figma component library:
https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/DDS---Core-Components?node-id=7882%3A46619&t=gzm3ed7E13uV63R1-1
