### ISSUE TITLE
Specification for: Popover

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#60]
### What component is it that needs specification?

Popover

### Tasks

_Link to correct placement in our Figma component library._
https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/DDS---Core-Components?node-id=10702%3A68732&t=gzm3ed7E13uV63R1-1
![image](https://user-images.githubusercontent.com/1464915/212768091-40555f26-a65b-4adc-aa59-eced370b1e07.png)

- [ ] Design is fully specified in Figma
  - [ ] Design component with all relevant states
  - [ ] Do a accessibility test of the sketches
  - [ ] Functionality/animation is described and prototyped if relevant
  - [ ] Describe keyboardnavigation (Only relevant if its not a native html component)
- [ ] Write acceptance criteria and link to Figma   

### SVG

- [ ] If there are used any svgs in this component is it available for the developer?
