### ISSUE TITLE
New component: Link

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystem#62]
### What component is it that needs specification?

Link

### Tasks

_Link to correct placement in our Figma component library._
- [ ] Design is fully specified in Figma
  - [ ] Design component with all relevant states
  - [ ] Do a accessibility test of the sketches
  - [ ] Functionality/animation is described and prototyped if relevant
  - [ ] Describe keyboardnavigation (Only relevant if its not a native html component)
- [ ] Write acceptance criteria and link to Figma   

### SVG

- [ ] If there are used any svgs in this component is it available for the developer?
