### ISSUE TITLE
Accordion: Write guidelines for usage

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#625]
```[tasklist]
### Tasks
- [x] Gather information for description
- [x] Reformulate
- [x] Confer with Dorte before submitting to review
- [x] Submit for review
- [x] Make changes after reveiw
- [ ] Move guidelines from Figma to Storybook
```

**Comment by Ildest** [comment]
Komponentbeskrivelse lagt i Figma - klar til gjennomgang av designleder/accordion-ansvarlig designer.

**Comment by Ildest** [comment]
Hei! Da har jeg svart på spørsmål i kommentaren i Figma og endret det jeg kunne + lagt inn eksempeltekster. Det gjenstår et par kommentarer med svar som du må se på. Vil du vente med å flytte til Done til dere har lagt den over i Storybook, @mrosvik ?

**Comment by mrosvik** [comment]
@Ildest Veldig bra!  🙌  Ja, tenker vi flytter til done når det er lagt på Storybook :) 

Vi må kanskje fjerne "Brukeren kan også velge chevron-ikonet (^). Noen bruker også + (plusstegn) og - (minustegn) for å vise åpne- og lukkefunksjonen." 

Her har vi tenkt at det konsekvent skal være chevron og at dette ikonet ikke skal byttes ut.

**Comment by Ildest** [comment]
Jepp, det kan dere bare fjerne. jeg tok det med fordi det sto i andres dokumentasjon av denne komponenten og at man fremdeles ser det i mange grensesnitt. Veldig glad hvis det kun er mulig å bruke bare ett ikon :-).
