### ISSUE TITLE
Figma Variables support

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#651]
Figma’s newest update features Variables, Figma’s version of design tokens. It allows you to create number, color, boolean and content variables. Tokens Studio for Figma will let you create variables based on your tokens. This works using the Themes feature. Read more: https://docs.tokens.studio/variables/creating-variables

NB: Does'nt support typography, shadows, borders yet.

![Image](https://github.com/digdir/designsystem/assets/1464915/7ce0ffc8-d8f2-4a56-a9fa-af8f3f9ca41e)

```[tasklist]
### Tasks
- [x] To make the convert work we have to create Theming groups ( #649 )
- [x] New branch in **_Design Tokens_**/[`Adding variables`](https://www.figma.com/file/eeznFkuH7UletQmhN174VR/branch/p7Qs9QLw5nA6zpZ9xNKZ16/Felles---Design-Tokens?type=design&node-id=6106%3A13775&mode=design&t=Abs4uuacwKHzCm4S-1)
- [x] Create variables (https://www.youtube.com/watch?v=a12TuEaiSqc)
- [ ] Test
``` 

https://github.com/digdir/designsystem/assets/1464915/dcb25a3f-164a-49b7-adaf-3ef88a9543a3

**Comment by mrosvik** [comment]
Jeg har begynt å tilpasse tokens-oppsettet ([#649](https://github.com/digdir/designsystem/pull/649)) for å kunne være i sync med variabler og collections i Figma, men tror ikke vi skal merge denne inn før vi har testet oppsettet noe mer.

I Figma ligger det en branch på Design Tokens som heter Adding variables. Test gjerne oppsettet i denne Figma-branchen: [https://www.figma.com/file/eeznFkuH7UletQmhN174VR/branch/p7Qs9QLw5nA6zpZ9xNKZ16/Fel[…]e=design&node-id=6116%3A14253&mode=design&t=4xOWeEDFCsljX5yN-1](https://www.figma.com/file/eeznFkuH7UletQmhN174VR/branch/p7Qs9QLw5nA6zpZ9xNKZ16/Felles---Design-Tokens?type=design&node-id=6116%3A14253&mode=design&t=4xOWeEDFCsljX5yN-1)
