### ISSUE TITLE
Specification for: Panel

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#84]
### Related issues or relevant information?

- See previous panel design from [altinn](https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/DDS---Core-Components?node-id=6616%3A26354&t=fgu4e3XDW9eMAE9U-1)
- https://design-system.service.gov.uk/components/panel/
- https://aksel.nav.no/komponenter/core/panel

### Design tasks

- [ ] Design is fully specified in Figma
  - [ ] Design component with all relevant states
  - [ ] Aaccessibility test of the sketches
  - [ ] Functionality/animation is described and prototyped if relevant    
  - [ ] If there are used any svgs in this component is it available for the developer? [Link]
  - [ ] Link to Figma design: [Link]
  - [ ] Pasted screenshot from Figma below :point_down:

### Development Tasks

- [ ] Implement in Storybook
- [ ] Make sure all variants/properties is possible to turn on/off
- [ ] Make sure the component is usable across different breakpoints/screen sizes
- [ ] Aaccessibility test of the code

### Accessibility tasks

- [ ] WCAG-review

**Comment by mrosvik** [comment]
Blir ikke en komponent i Felles designsystem
